[package]
name = "rustacean_downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
yt-dlp = { version = "1.4.7", features = ["tracing"] }
tokio = { version = "1.49.0", features = ["full"] }
axum = "0.7"
file-guard = "0.2"